remote_url = "urcs://urc-uefn.live.ucs.on.epicgames.com"
identity = "01993e28b6f07381b66fc5144232ed6e"

[store]
max_capacity = 10485760
eviction_delay = 10
max_size = 10737418240
compaction_delay = 30

[file]
direct_write = false
direct_io = false
flush_write = false
